apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-webapp
  name: simple-webapp-service
spec:
  ports:
  - nodePort: 30000
    port: 8080
    targetPort: 8080
  selector:
    app: simple-webapp
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-webapp
  name: simple-webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webapp
  template:
    metadata:
      labels:
        app: simple-webapp
    spec:
      containers:
      - image: kind-registry:5000/simple_webapp:1.0
        name: simple-webapp
        ports:
        - containerPort: 8080
